### ISSUE TITLE
Bug: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Katterinne** [KHanghoj/DamMet#1]
Dear Hanghoj,

This is to report a **bug in DamMet** that is preventing the successful use of the tool on real aDNA data.

**Briefly**, DamMet estDEAM stops when reading the reads and shows the error message: "**Segmentation fault (core dumped)**". This happens with different real aDNA sequencing data with an average read depth ranging from ~3.8X to ~50X, and using different computers (16 CPUs/32 GiB RAM and 32CPUs/256 GiB RAM) and OS (Linux Ubuntu, and MacOS). Interestingly, DamMet works fine for some samples and fails for others.

If you're interested in the details, let me walk you through it...

I have run DamMet on 16 real aDNA sequencing data (*input: BAM file of the alignment of the aDNA sequences against the human reference genome*) with an average read depth ranging from ~1.5X to ~50X. For 5 of these samples, DamMet worked just fine (both steps: estDEAM and estF). These 5 samples have an average read depth ranging from ~1.5X to ~10.6X. **On the other hand**, for the other 11 samples with an average read depth ranging from ~3.8X to ~50X, DamMet failed. DamMet estDEAM stops when reading the reads and shows the error message: "Segmentation fault (core dumped)". I tried to run DamMet again with these samples in different computers with the following specifications: 16 CPUs/32 GiB RAM and 32CPUs/256 GiB RAM, Linux (Ubuntu) and MacOS. Same thing happened every time. The example command line I was using:

```
DamMet estDEAM -b sample.bam -r human_ref_genome.fasta -cf chromosomes.list -O sample -R sample_RGs.list
```

Notes:
- I was using `-cf` with a list of all chromosomes `chromosomes.list`(1 to 22, X, Y, and MT).
- I tried with and without providing a read group list (`-R`). It didn't make a difference.

Additional information I have from experimenting with the tool, trying to understand why it wouldn't work...

**Additionally**, even knowing that DamMet runs on one chromosome at a time, I tried again using the *-c* option to run one chromosome at a time. By doing this I could run DamMet with most of the chromosomes of the samples that previously failed, but for several of the chromosomes, again, DamMet will stop when reading the reads (either giving a read group list or not) and shows the error message: "Segmentation fault (core dumped)". The number and identity of the chromosomes that failed would depend on each sample. The example command line I was using:

```
DamMet estDEAM -b sample.bam -r human_ref_genome.fasta -c 1 -O sample_chr1 -R sample_RGs.list
```

**Next**, I tried again, this time using the *-L* option to filter the reads by length for those chromosomes that failed. I found that, by trying increasing read length values on each chromosome, eventually DamMet will run successfully. The example command line I was using:

```
DamMet estDEAM -b sample.bam -r human_ref_genome.fasta -c 6 -L 80 -O sample_chr6 -R sample_RGs.list
```

Notes:
- I used the `-L` option starting from `35` with an increase of `5` (the minimum read length in all my samples is 30).

Finally, when I wanted to run DamMet's second step on the same chromosomes I had to run independently and with a read length filter for the first step, it was necessary to do the same for estF to work.

**Example data for reproducing error...**

Using [this Dropbox link](https://www.dropbox.com/s/ati688djaottcl7/example_data.zip?dl=0) you can download  a zip file with the necessary files to reproduce the error:

The files you will find:
Alignment file and its index: `SF12_DS_05.bam`, `SF12_DS_05.bam.bai`
(This sample has an average read depth of ~5X)
Human reference fasta file and index: `hs37d5.fa`, `hs37d5.fa.fai`
Read group list file: `SF12DS05_RGs.list`

When running DamMet one chromosome at a time using the *-c* option, the chromosome that fails is: 6. 

```
DamMet estDEAM -b SF12_DS_05.bam -r hs37d5.fa -c 6 -O SF12DS05_chr6 -R SF12DS05_RGs.list
```

Note: It works when using `-L 80`.

---

I don't want to have to reduce the total number of reads in order to run DamMet, for some samples and chromosomes I had to use high read length filters for DamMet to work. This is wasting valuable information. Besides, I didn't find a correlation between BAM file size or depth and the bug. Either regarding computational resources.

I hope something can be done about this, I'm looking forward to use DamMet to infer methylation in my ancient genomes, which I need for further analysis. Please, let me know if you need more details or if I can help somehow.

Thank you very much in advance. And thanks for your work in epiPALEOMIX, gargammel, and DamMet!

Regards,
Katterinne

**Comment by KHanghoj** [comment]
Hi Katterinne,

first of all thanks for the in depth bug report. It seems peculiar, but clearly looks like a bug. Ill investigate. 

Thank you providing data to reproduce the bug. it makes it way easier to detect the error. However, it seems like the provided bam is truncated. 

`samtools quickcheck SF12_DS_05.bam` returns *SF12_DS_05.bam was missing EOF block when one should be present.*

I also tried to jump to chromosome 6: samtools view SF12_DS_05.bam 6 but it didnt work. Would it be possible to send me the bam file again. If the dammet bug can be reproduced baesd on data from chromosome 6, you can just send reads mapping to that. 

We will fix this error as soon as  we can reproduce it :).

Kristian

When

**Comment by Katterinne** [comment]
Hi Kristian,

Thanks a lot for the positive and quick reply! I'm so sorry the bam file I provided it's truncated, honestly, don't know what happened there. I'm trying with another sample now, it also produce the error I'm reporting.

This sample also has an average read depth of ~5X, and the chromosomes failing are: 19 and 8.

Download links:
[aligment file](https://www.dropbox.com/s/7z3u92wnq1zybd0/Kir26.hg19.sort.MkDup.merged_realg.bam?dl=0)
[bam.bai](https://www.dropbox.com/s/zes2cjtj4k8w6wb/Kir26.hg19.sort.MkDup.merged_realg.bam.bai?dl=0)
[read group list file](https://www.dropbox.com/s/j84obtnuhq33z56/Kir26_RGs.list?dl=0)

I hope the file are fine this time, otherwise, please let me know and I'll find another way to share them with you.

Thank you!

Katterinne

**Comment by Katterinne** [comment]
Hi Kristian,

Just in case you need it and following the alternative you suggested, here is the fastq files with the reads mapping to chromosomes 19 and 8 from the bam file I sent in my last message.

Download links:
[reads mapping to chr8](https://www.dropbox.com/s/qrn87fkpx8k37u7/Kir26_chr8.fastq?dl=0)
[reads mapping to chr19](https://www.dropbox.com/s/idl9svbxnbgwp0u/Kir26_chr19.fastq?dl=0)

Thank you!

Katterinne

**Comment by KHanghoj** [comment]
Hi again,

I have had a look and it seems like some reads in the BAM file is one big insertion. here is an example:

```
J00121:155:H2FTLBBXY:2:2120:18832:27865 16      19      29379263        47      78I     *       0       0       GGCTCACACACGACGCCCCTGCTCCCTCAGGACCCTGGGCAGAGTCCCGGCTCACACACGACGCCCCTGCTCCCTCAG  FJJJJJJJFJJJFFJJFJJJJJFJJJJFJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFFFAA      X0:i:1  X1:i:0  OC:Z:78M        RG:Z:SL22_6_12_L2_R1_001_cMaPZdkPnjey_trim      XG:i:0  NM:i:78 XM:i:3  XO:i:0  XT:A:U
```
DamMet doesnt know how to handle this so I have added a check so that these reads are removed. chr19 is now running.
But it seems like the BAM file has been modified since mapping. The original cigar is removed (see  OC tag with cigar 78M) and replaced by one large insertion. 

Let me know if you encounter other problems.

Kristian

**Comment by Katterinne** [comment]
Hi Kristian,

Sorry for the slow reply; I was excited trying DamMet's upgraded version with the samples that failed before. DamMet estDEAM and estF ran successfully with all the samples, this is great! Thank you very, very much! :D

You're right, i'm sorry I didn't mention it before. We do modify the BAM files after mapping before further analysis (e.g., variant call). What you found, probably happened during the local realignment step. Do you think this could significantly affect DamMet results?

Thanks again! Wish you the best!

Katterinne

**Comment by KHanghoj** [comment]
That sounds reasonable. I think/hope that local realignment can only improve the accuracy. I havent explored it. As it is now, the reads only including an Insertion/deletion are just excluded. 

Feel free to reopen this issue, if you encounter a similar issue. Or start a new one :)

Best,
kristain
